site_name: 'VSpal'
site_description: 'A library for handling vague (fuzzy) spatial data types and their operations'
site_author: 'Anderson Chaves Carniel'
site_url: 'https://accarniel.github.io/SpatialPlateauAlgebra'
copyright: 'Copyright &copy; 2014 - 2018 Anderson Chaves Carniel'
nav:
    - Home: index.md
    - Building Fuzzy Regions: building_fuzzy_regions/building_plateau_regions.md
    - Contact: contact.md
    - Publications: publications.md
repo_url: https://github.com/accarniel/SpatialPlateauAlgebra
repo_name: 'accarniel/SpatialPlateauAlgebra'
theme: 
  name: 'material'
  palette:
    primary: 'light blue'
    accent: 'deep orange'
extra:
  social:
    - type: 'github'
      link: 'https://github.com/accarniel/SpatialPlateauAlgebra/'
extra_css:
  - 'css/index.css'
  - 'css/colors.css'
edit_uri: '' #if we want links to the github page, we exclude this line
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: "#"
      separator: "_"
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde